@link = http://localhost:3000

### Delete stock data
DELETE {{link}}/api/stock-prices?stock=vrtx&stock=wba&stock=wdc
Accept:  */*

### get 1 stock
GET {{link}}/api/stock-prices?stock=wdc
Accept:  */*

### invalid stock
GET {{link}}/api/stock-prices?stock=abcdef
Accept:  */*

### get 2 stock
GET {{link}}/api/stock-prices?stock=vrtx&stock=wba
Accept:  */*

### like stock
GET {{link}}/api/stock-prices?stock=vrtx&like=true
Accept:  */*

### like multi stock
GET {{link}}/api/stock-prices?stock=vrtx&stock=wba&like=true
Accept:  */*
